name: ML Model Training CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install scikit-learn pandas joblib
    - name: Train model
      run: python ml_training.py
    - name: Upload trained model artifact
      uses: actions/upload-artifact@v2
      with:
        name: trained-model
        path: model.joblib
